spring:
  devtools:
    restart:
      enabled: true
  application:
    name: JournalAppPractice
  data:
    redis:
      url: redis://default:SvVZBbsguMeJexZjhWfQx5TDZbECitcL@redis-11922.crce182.ap-south-1-1.ec2.redns.redis-cloud.com:11922
    mongodb:
      uri: mongodb+srv://sdflkjsldf:6MzvqqxfWqX9UFdJ@cluster0.lt8gotz.mongodb.net/journal_db?retryWrites=true&w=majority
      auto-index-creation: true

quote:
  api:
    key: ${QUOTE_API_KEY:dummy-quote-api-key}

weather:
  api:
    key: ${WEATHER_API_KEY:weather-quote-api-key}


server:
  port: 8080

app:
  jwt:
    secret: devSecretKeyCha222@#@#$@jdjflsdjsdfngeThis123
    expiration: 86400

sendgrid:
  api-key: ${SENDGRID_API_KEY:dummy-key-for-testing}

